Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 9.101684093475342 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 6.610006093978882 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 5.628590106964111 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 5.709880113601685 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 4.894751310348511 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 5.532320976257324 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 8.281992197036743 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds
Kimi-K2 selected action:  ActionType.ROLL in 0 seconds
GPT-5 selected action:  ActionType.ROLL in 0 seconds
Claude-Sonnet-4 selected action:  ActionType.ROLL in 0 seconds
Gemini-2.5-Pro selected action:  ActionType.ROLL in 0 seconds